export const COURSE_CATALOG = {
  backend_api_cert: {
    title: "freeCodeCamp Back End Development and APIs Certification",
    link: "https://www.freecodecamp.org/learn/back-end-development-and-apis/",
    level: "Intermediate",
    type: "certification",
    provider: "freeCodeCamp",
  },
  testing_guided: {
    title: "Testing Guided Practice",
    link: "https://playwright.dev/docs/intro",
    level: "Intermediate",
    type: "guide",
    provider: "Playwright",
  },
  deployment_workflow: {
    title: "Deployment Workflow Practice",
    link: "https://docs.github.com/en/actions",
    level: "Intermediate",
    type: "guide",
    provider: "GitHub Docs",
  },
  service_architecture: {
    title: "Service Architecture Guide",
    link: "https://roadmap.sh/system-design",
    level: "Advanced",
    type: "guide",
    provider: "roadmap.sh",
  },
  reliability_engineering: {
    title: "Reliability Engineering Guide",
    link: "https://sre.google/workbook/table-of-contents/",
    level: "Advanced",
    type: "guide",
    provider: "Google SRE",
  },
  python_foundations: {
    title: "Python for Everybody",
    link: "https://www.kaggle.com/learn/python",
    level: "Beginner",
    type: "course",
    provider: "Kaggle",
  },
  sql_foundations: {
    title: "Databases and SQL for Data Science",
    link: "https://www.kaggle.com/learn/intro-to-sql",
    level: "Beginner",
    type: "course",
    provider: "Kaggle",
  },
  react_foundations: {
    title: "React - The Complete Guide",
    link: "https://react.dev/learn",
    level: "Intermediate",
    type: "course",
    provider: "React Docs",
  },
  javascript_foundations: {
    title: "Modern JavaScript Bootcamp",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
    level: "Beginner",
    type: "course",
    provider: "MDN",
  },
  responsive_web_cert: {
    title: "Responsive Web Design",
    link: "https://www.freecodecamp.org/learn/responsive-web-design/",
    level: "Beginner",
    type: "certification",
    provider: "freeCodeCamp",
  },
  docker_foundations: {
    title: "Docker or Cloud Fundamentals",
    link: "https://skillsbuild.org/",
    level: "Intermediate",
    type: "course",
    provider: "IBM SkillsBuild",
  },
  cloud_practitioner: {
    title: "AWS Cloud Practitioner Essentials",
    link: "https://aws.amazon.com/training/digital/",
    level: "Intermediate",
    type: "course",
    provider: "AWS Skill Builder",
  },
  postman_api_foundations: {
    title: "Postman API Fundamentals",
    link: "https://learning.postman.com/docs/getting-started/overview/",
    level: "Beginner",
    type: "course",
    provider: "Postman",
  },
  power_bi_cert: {
    title: "Microsoft Power BI Data Analyst",
    link: "https://learn.microsoft.com/en-us/training/powerplatform/power-bi/",
    level: "Intermediate",
    type: "certification",
    provider: "Microsoft Learn",
  },
  data_analytics_cert: {
    title: "Google Data Analytics Certificate",
    link: "https://www.coursera.org/professional-certificates/google-data-analytics",
    level: "Intermediate",
    type: "certification",
    provider: "Coursera",
  },
  seo_foundations: {
    title: "Google SEO Fundamentals",
    link: "https://developers.google.com/search/docs/fundamentals/seo-starter-guide",
    level: "Beginner",
    type: "guide",
    provider: "Google Search Central",
  },
  excel_foundations: {
    title: "Excel Skills for Business",
    link: "https://support.microsoft.com/en-us/office/excel-video-training-9bc05390-e94c-46af-a5b3-d7c22f6990bb",
    level: "Beginner",
    type: "course",
    provider: "Microsoft Support",
  },
  financial_modeling_foundations: {
    title: "Financial Modeling for Beginners",
    link: "https://corporatefinanceinstitute.com/resources/financial-modeling/what-is-financial-modeling/",
    level: "Intermediate",
    type: "course",
    provider: "CFI",
  },
  git_foundations: {
    title: "Version Control with Git",
    link: "https://git-scm.com/docs/gittutorial",
    level: "Beginner",
    type: "course",
    provider: "git-scm",
  },
  linux_foundations: {
    title: "Linux for Beginners",
    link: "https://linuxjourney.com/",
    level: "Beginner",
    type: "course",
    provider: "Linux Journey",
  },
  figma_foundations: {
    title: "UI/UX Design with Figma",
    link: "https://help.figma.com/hc/en-us/categories/360002051613-Designing-in-Figma",
    level: "Beginner",
    type: "course",
    provider: "Figma Help",
  },
  hubspot_crm_cert: {
    title: "HubSpot CRM Certification",
    link: "https://knowledge.hubspot.com/crm-setup/set-up-your-crm",
    level: "Beginner",
    type: "certification",
    provider: "HubSpot",
  },
  google_analytics_cert: {
    title: "Google Analytics Certification",
    link: "https://skillshop.docebosaas.com/learn/course/external/view/elearning/118/google-analytics-certification",
    level: "Intermediate",
    type: "certification",
    provider: "Google Skillshop",
  },
  google_analytics_prep: {
    title: "Google Analytics Certification Prep",
    link: "https://skillshop.docebosaas.com/learn/course/external/view/elearning/118/google-analytics-certification",
    level: "Intermediate",
    type: "course",
    provider: "Google Skillshop",
  },
};

export const LEGACY_COURSE_TITLE_ALIASES = {
  "rest api guided course": "backend_api_cert",
  "fastapi or backend api path": "backend_api_cert",
  "back end development and apis certification (freecodecamp)": "backend_api_cert",
  "fastapi beyond crud": "backend_api_cert",
  "api design patterns": "backend_api_cert",
  "api troubleshooting practice": "backend_api_cert",
  "postman api fundamentals": "postman_api_foundations",
  "testing and reliability guides": "reliability_engineering",
  "frontend testing essentials": "testing_guided",
  "deployment workflow practice": "deployment_workflow",
  "production app deployment": "deployment_workflow",
  "backend case studies": "service_architecture",
  "system design interview practice": "service_architecture",
  "python developer fundamentals": "python_foundations",
  "python application fundamentals": "python_foundations",
  "sql query practice": "sql_foundations",
  "database schema design basics": "sql_foundations",
  "react developer path": "react_foundations",
  "modern react workflow": "react_foundations",
  "responsive web design": "responsive_web_cert",
  "responsive web design fundamentals": "responsive_web_cert",
  "docker or cloud fundamentals": "docker_foundations",
  "cloud practitioner basics": "cloud_practitioner",
  "excel skills for business": "excel_foundations",
  "google data analytics certificate": "data_analytics_cert",
  "microsoft power bi data analyst": "power_bi_cert",
  "google seo fundamentals": "seo_foundations",
  "financial modeling for beginners": "financial_modeling_foundations",
  "hubspot crm certification": "hubspot_crm_cert",
  "linux and command-line basics": "linux_foundations",
  "git workflow practice": "git_foundations",
  "ui/ux design with figma": "figma_foundations",
  "google analytics certification prep": "google_analytics_prep",
  "google analytics certification": "google_analytics_cert",
};
